/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 lamb.gltf 
Author: Jonrss (https://sketchfab.com/huy14320000006)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lamborghini-venevo-5884f95259ff411c95510cdde5ede33e
Title: Lamborghini venevo
*/

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 lamb.gltf 
Author: Jonrss (https://sketchfab.com/huy14320000006)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lamborghini-venevo-5884f95259ff411c95510cdde5ede33e
Title: Lamborghini venevo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/lamb.gltf')

  
  return (
    <group {...props} dispose={null}>
      <group position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Vt_Liu.002']} />
      </group>
      <group position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]}>
        <mesh geometry={nodes.Object_15.geometry} material={materials.lamp} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Vt_Liu} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Vt_Liu.001']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.engine} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.wheel} position={[0.915, 1.325, -4.521]} rotation={[1.578, 0, -0.035]} scale={[-3.653, 3.653, 3.653]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.material_5} position={[0.915, 1.325, -4.521]} rotation={[1.578, 0, -0.035]} scale={[-3.653, 3.653, 3.653]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.material_9} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.material_10} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.material_11} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.material_12} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.glass} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.material_14} position={[0.891, 1.329, -5.196]} rotation={[1.578, 0, -0.035]} scale={[-3.653, 3.653, 3.653]} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.material_15} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.logo} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.material_17} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.material_18} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.material_19} position={[0.891, 1.329, -5.196]} rotation={[1.578, 0, -0.035]} scale={[-3.653, 3.653, 3.653]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.glass} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.material_20} position={[-1.716, 0.502, 0.053]} rotation={[1.578, 0, -0.035]} scale={[-3.366, 3.366, 3.366]} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.wheel} position={[1.266, 1.182, 4.529]} rotation={[1.578, 0, -0.035]} scale={[-3.274, 3.274, 3.274]} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.material_5} position={[1.266, 1.182, 4.529]} rotation={[1.578, 0, -0.035]} scale={[-3.274, 3.274, 3.274]} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.material_14} position={[1.248, 1.185, 4.003]} rotation={[1.578, 0, -0.035]} scale={[-3.031, 3.031, 3.031]} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.material_19} position={[1.248, 1.185, 4.003]} rotation={[1.578, 0, -0.035]} scale={[-3.031, 3.031, 3.031]} />
    </group>
  )
}

useGLTF.preload('/lamb.gltf')